# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-cageseq-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
- asn1crypto=0.24.0
- bedtools=2.27.1
- blas=1.0
- bz2file=0.98
- bzip2=1.0.6
- ca-certificates=2019.3.9
- certifi=2019.3.9
- cffi=1.12.2
- cryptography=2.6.1
- curl=7.64.0
- cutadapt=2.1
- dbus=1.13.2
- decorator=4.4.0
- dnaio=0.3
- conda-forge::expat=2.2.5
- fastqc=0.11.8
- font-ttf-dejavu-sans-mono=2.37
- fontconfig=2.13.0
- freetype=2.9.1
- gettext=0.19.8.1
- glib=2.56.2
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- icu=58.2
- intel-openmp=2019.3
- jinja2=2.10.1
- jpeg=9c
- krb5=1.16.1
- libcurl=7.64.0
- libdeflate=1.0
- libedit=3.1.20181209
- libffi=3.2.1
- libgcc-ng=8.2.0
- libgfortran-ng=7.3.0
- libiconv=1.15
- libpng=1.6.36
- libssh2=1.8.0
- libstdcxx-ng=8.2.0
- libuuid=1.0.3
- libxcb=1.13
- libxml2=2.9.9
- markupsafe=1.1.1
- mkl=2019.3
- mkl_fft=1.0.10
- mkl_random=1.0.2
- ncurses=6.1
- numpy-base=1.16.2
- openjdk=8.0.152
- openssl=1.1.1b
- pandas=0.24.2
- pcre=8.43
- perl=5.26.2
- pigz=2.4
- pip=19.0.3
- pthread-stubs=0.4
- pycparser=2.19
- pyopenssl=19.0.0
- pyparsing=2.4.0
- pyqt=5.6.0
- pysocks=1.6.8
- python=3.6.8
- python-dateutil=2.8.0
- qt=5.6.3
- readline=7.0
- requests=2.21.0
- samtools=1.9
- setuptools=40.8.0
- sip=4.18.1
- sqlite=3.27.2
- star=2.7.0f
- tk=8.6.8
- tornado=6.0.2
- wheel=0.33.1
- xopen=0.5.0
- xorg-libxau=1.0.9
- xorg-libxdmcp=1.1.3
- xz=5.2.4
- yaml=0.1.7
- zlib=1.2.11
- pip:
  - chardet==3.0.4
  - click==7.0
  - colormath==3.0.0
  - cycler==0.10.0
  - future==0.17.1
  - idna==2.8
  - kiwisolver==1.0.1
  - lzstring==1.0.4
  - markdown==3.1
  - matplotlib==2.2.4
  - multiqc==1.7
  - networkx==2.2
  - numpy==1.16.2
  - pytz==2019.1
  - pyyaml==5.1
  - simplejson==3.16.0
  - six==1.12.0
  - spectra==0.0.11
  - urllib3==1.24.1




