# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-cageseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- bedtools=2.27.1
- cutadapt=1.18
- fastqc=0.11.8
- libdeflate=1.0
- multiqc=0.9.1a0
- samtools=1.9
- simplejson=3.8.1
- star=2.7.0e
- xopen=0.5.0
- backports=1.0
- backports.functools_lru_cache=1.5
- backports_abc=0.5
- blas=1.0
- bz2file=0.98
- bzip2=1.0.6
- ca-certificates=2019.1.23
- certifi=2019.3.9
- click=7.0
- curl=7.64.0
- cycler=0.10.0
- dbus=1.13.6
- expat=2.2.6
- font-ttf-dejavu-sans-mono=2.37
- fontconfig=2.13.0
- freetype=2.9.1
- functools32=3.2.3.2
- futures=3.2.0
- git=2.20.1
- glib=2.56.2
- gst-plugins-base=1.14.0
- gstreamer=1.14.0
- icu=58.2
- intel-openmp=2019.3
- jinja2=2.10
- jpeg=9b
- kiwisolver=1.0.1
- krb5=1.16.1
- libcurl=7.64.0
- libedit=3.1.20181209
- libffi=3.2.1
- libgcc-ng=8.2.0
- libgfortran-ng=7.3.0
- libpng=1.6.36
- libssh2=1.8.0
- libstdcxx-ng=8.2.0
- libuuid=1.0.3
- libxcb=1.13
- libxml2=2.9.9
- markupsafe=1.1.1
- matplotlib=2.2.3
- mkl=2019.3
- mkl_fft=1.0.10
- mkl_random=1.0.2
- ncurses=6.1
- numpy=1.16.2
- numpy-base=1.16.2
- openjdk=8.0.152
- openssl=1.1.1b
- pcre=8.43
- perl=5.26.2
- pigz=2.4
- pip=19.0.3
- pyparsing=2.3.1
- pyqt=5.9.2
- python=2.7.16
- python-dateutil=2.8.0
- pytz=2018.9
- pyyaml=5.1
- qt=5.9.7
- readline=7.0
- setuptools=40.8.0
- singledispatch=3.4.0.3
- sip=4.19.8
- six=1.12.0
- sqlite=3.27.2
- subprocess32=3.5.3
- tk=8.6.8
- tornado=5.1.1
- wheel=0.33.1
- xz=5.2.4
- yaml=0.1.7
- zlib=1.2.11


